# Generated by Django 3.1.1 on 2020-09-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200905_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discraption',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
