# Generated by Django 3.1.1 on 2020-09-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200906_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Discountprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
