# Generated by Django 3.1.1 on 2020-09-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_discountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ISBestseller',
            field=models.BooleanField(default=False, verbose_name='Best seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='ISNew',
            field=models.BooleanField(default=True, verbose_name='New Product'),
        ),
    ]
