# Generated by Django 3.1.1 on 2020-09-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200906_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discraption',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
