# Generated by Django 3.1.1 on 2020-09-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200906_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='discraption',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
