# Generated by Django 3.1.1 on 2020-09-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20200907_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('books', 'books'), ('Arts & Crafts', 'Arts & Crafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Swimming', 'Swimming'), ('Wrestling', 'Wrestling'), ('Tv', 'Tv'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Computers', 'Computers'), ("Women's Fashion", "Women's Fashion"), ("Men's Fashion", "Men's Fashion"), ("Girl's Fashion", "Girl's Fashion"), ("Boy's Fashion", "Boy's Fashion"), ('Health & Household', 'Health & Household'), ('Home & Kitchen', 'Home & Kitchen'), ('Industrial & Scientific', 'Industrial & Scientific'), ('Luggage', 'Luggage'), ('Movies & Television', 'Movies & Television'), ('Music, CDs & Vinyl', 'Music, CDs & Vinyl'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Tools & Home Improvement', 'Tools & Home Improvement'), ('Toys & Games', 'Toys & Games'), ('Video Games', 'Video Games'), ('Phone&Accessories', 'Phone&Accessories'), ('Travel', 'Travel'), ('Dance sport', 'Dance sport')], max_length=255),
        ),
    ]
