# Generated by Django 3.1.1 on 2020-09-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20200907_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categores',
        ),
    ]
