# Generated by Django 3.1.1 on 2020-09-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20200907_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categores',
            new_name='category',
        ),
    ]
