# Generated by Django 3.1.1 on 2020-09-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20200907_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Discountprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('books', 'books'), ('Arts & Crafts', 'Arts & Crafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Swimming', 'Swimming'), ('Wrestling', 'Wrestling'), ('Tv', 'Tv'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Computers', 'Computers'), ("Women's Fashion", "Women's Fashion"), ("Men's Fashion", "Men's Fashion"), ("Girl's Fashion", "Girl's Fashion"), ("Boy's Fashion", "Boy's Fashion"), ('Health & Household', 'Health & Household'), ('Home & Kitchen', 'Home & Kitchen'), ('Industrial & Scientific', 'Industrial & Scientific'), ('Luggage', 'Luggage'), ('Movies & Television', 'Movies & Television'), ('Music CDs and  Vinyl', 'Music CDs and  Vinyl'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Tools and Home Improvement', 'Tools and Home Improvement'), ('Toys and Games', 'Toys and Games'), ('Video Games', 'Video Games'), ('Phone and accessories', 'Phone and accessories'), ('Travel', 'Travel'), ('Dance sport', 'Dance sport')], max_length=255),
        ),
    ]
