# Generated by Django 3.1.1 on 2020-09-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_recommendations_for_you'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='head_titel',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
