# Generated by Django 3.1.1 on 2020-09-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_category_head_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='titel',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
