# Generated by Django 3.1.1 on 2020-09-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20200912_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swiber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='More Image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='More Image')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='More Image')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='More Image')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='More Image')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='', verbose_name='More Image')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='', verbose_name='More Image')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='', verbose_name='More Image')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='', verbose_name='More Image')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='', verbose_name='More Image')),
                ('category', models.CharField(choices=[('Arts and Crafts', 'Arts and Crafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty Personal Care', 'Beauty Personal Care'), ('Swimming', 'Swimming'), ('Wrestling', 'Wrestling'), ('Television', 'Television'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Computers', 'Computers'), ("Women's Fashion", "Women's Fashion"), ('Mens Fashion', 'Mens Fashion'), ('Girls Fashion', 'Girls Fashion'), ('Boys Fashion', 'Boys Fashion'), ('Health and Household', 'Health and Household'), ('Home and Kitchen', 'Home and Kitchen'), ('Industrial and Scientific', 'Industrial and Scientific'), ('Luggage', 'Luggage'), ('Movies', 'Movies'), ('Music or CDs and  Vinyl', 'Music or CDs and  Vinyl'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Tools and Home Improvement', 'Tools and Home Improvement'), ('Toys and Games', 'Toys and Games'), ('Video Games', 'Video Games'), ('Phone and accessories', 'Phone and accessories'), ('Travel', 'Travel'), ('Dance sport', 'Dance sport'), ('Clothes', 'Clothes')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Discountprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Discount price '),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Arts and Crafts', 'Arts and Crafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty Personal Care', 'Beauty Personal Care'), ('Swimming', 'Swimming'), ('Wrestling', 'Wrestling'), ('Television', 'Television'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Computers', 'Computers'), ("Women's Fashion", "Women's Fashion"), ('Mens Fashion', 'Mens Fashion'), ('Girls Fashion', 'Girls Fashion'), ('Boys Fashion', 'Boys Fashion'), ('Health and Household', 'Health and Household'), ('Home and Kitchen', 'Home and Kitchen'), ('Industrial and Scientific', 'Industrial and Scientific'), ('Luggage', 'Luggage'), ('Movies', 'Movies'), ('Music or CDs and  Vinyl', 'Music or CDs and  Vinyl'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Tools and Home Improvement', 'Tools and Home Improvement'), ('Toys and Games', 'Toys and Games'), ('Video Games', 'Video Games'), ('Phone and accessories', 'Phone and accessories'), ('Travel', 'Travel'), ('Dance sport', 'Dance sport'), ('Clothes', 'Clothes')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recommendations_for_you',
            name='category',
            field=models.CharField(choices=[('Arts and Crafts', 'Arts and Crafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty Personal Care', 'Beauty Personal Care'), ('Swimming', 'Swimming'), ('Wrestling', 'Wrestling'), ('Television', 'Television'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Computers', 'Computers'), ("Women's Fashion", "Women's Fashion"), ('Mens Fashion', 'Mens Fashion'), ('Girls Fashion', 'Girls Fashion'), ('Boys Fashion', 'Boys Fashion'), ('Health and Household', 'Health and Household'), ('Home and Kitchen', 'Home and Kitchen'), ('Industrial and Scientific', 'Industrial and Scientific'), ('Luggage', 'Luggage'), ('Movies', 'Movies'), ('Music or CDs and  Vinyl', 'Music or CDs and  Vinyl'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Tools and Home Improvement', 'Tools and Home Improvement'), ('Toys and Games', 'Toys and Games'), ('Video Games', 'Video Games'), ('Phone and accessories', 'Phone and accessories'), ('Travel', 'Travel'), ('Dance sport', 'Dance sport'), ('Clothes', 'Clothes')], max_length=255),
        ),
    ]
