# Generated by Django 3.1.1 on 2020-09-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20200915_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='head_titel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='titel',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
