# Generated by Django 3.1.1 on 2020-09-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20200917_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swiber_bags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='Image Of Product')),
                ('category', models.CharField(choices=[('Arts and Crafts', 'Arts and Crafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty Personal Care', 'Beauty Personal Care'), ('Swimming', 'Swimming'), ('Wrestling', 'Wrestling'), ('Television', 'Television'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Computers', 'Computers'), ('Womens Fashion', 'Womens Fashion'), ('Mens Fashion', 'Mens Fashion'), ('Girls Fashion', 'Girls Fashion'), ('Boys Fashion', 'Boys Fashion'), ('Health and Household', 'Health and Household'), ('Home and Kitchen', 'Home and Kitchen'), ('Industrial and Scientific', 'Industrial and Scientific'), ('Luggage', 'Luggage'), ('Movies', 'Movies'), ('Music or CDs and  Vinyl', 'Music or CDs and  Vinyl'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Tools and Home Improvement', 'Tools and Home Improvement'), ('Toys and Games', 'Toys and Games'), ('Video Games', 'Video Games'), ('Phone and accessories', 'Phone and accessories'), ('Travel', 'Travel'), ('Dance sport', 'Dance sport'), ('Clothes', 'Clothes')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Swiber',
        ),
    ]
