# Generated by Django 3.1.1 on 2020-09-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20200922_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Swiber_Coputers',
        ),
    ]
