# Generated by Django 3.1.1 on 2020-09-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_oneprouduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneProuduct',
        ),
    ]
