# Generated by Django 3.1.1 on 2020-09-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reat1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
