# Generated by Django 3.1.1 on 2020-09-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_comment_reat1'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reat2',
            field=models.BooleanField(default=True, verbose_name='New Product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reat3',
            field=models.BooleanField(default=True, verbose_name='New Product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reat1',
            field=models.BooleanField(default=True, verbose_name='New Product'),
        ),
    ]
