# Generated by Django 3.1.1 on 2020-09-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_auto_20200927_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reat4',
            field=models.BooleanField(default=False, verbose_name='reat4'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reat5',
            field=models.BooleanField(default=False, verbose_name='reat5'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reat1',
            field=models.BooleanField(default=False, verbose_name='reat1'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reat2',
            field=models.BooleanField(default=False, verbose_name='reat2'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reat3',
            field=models.BooleanField(default=False, verbose_name='reat3'),
        ),
    ]
