# Generated by Django 3.1.1 on 2020-09-28 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0048_auto_20200927_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_owner', to='auth.user'),
            preserve_default=False,
        ),
    ]
