# Generated by Django 3.1.1 on 2020-09-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_product_oner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
