# Generated by Django 3.1.1 on 2020-10-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_auto_20200930_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='head_titel',
        ),
        migrations.RemoveField(
            model_name='category',
            name='titel',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('name', 'name')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recommendations_for_you',
            name='category',
            field=models.CharField(choices=[('name', 'name')], max_length=255),
        ),
        migrations.AlterField(
            model_name='swiber_bags',
            name='category',
            field=models.CharField(choices=[('name', 'name')], max_length=255),
        ),
    ]
