# Generated by Django 3.1.1 on 2020-10-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_bannerevryweak'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerevryweak',
            name='HashTag',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Hash Tag Important '),
        ),
    ]
