# Generated by Django 3.1.1 on 2020-10-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_auto_20201031_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='Category Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='Title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
