# Generated by Django 3.1.1 on 2020-11-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_auto_20201031_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerevryweak',
            name='category',
            field=models.CharField(choices=[('Arts and Crafts', 'Arts and Crafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty Personal Care', 'Beauty Personal Care'), ('Books', 'Books'), ('Boys Fashion', 'Boys Fashion'), ('Computers', 'Computers'), ('Clothes', 'Clothes'), ('Dance sport', 'Dance sport'), ('Electronics', 'Electronics'), ('Girls Fashion', 'Girls Fashion'), ('Health and Household', 'Health and Household'), ('Home and Kitchen', 'Home and Kitchen'), ('Industrial and Scientific', 'Industrial and Scientific'), ('Luggage', 'Luggage'), ('Music or CDs and Vinyl', 'Music or CDs and Vinyl'), ('Movies', 'Movies'), ('Mens Fashion', 'Mens Fashion'), ('Phone and accessories', 'Phone and accessories'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Swimming', 'Swimming'), ('Television', 'Television'), ('Toys and Games', 'Toys and Games'), ('Travel', 'Travel'), ('Tools and Home Improvement', 'Tools and Home Improvement'), ('Video Games', 'Video Games'), ('Womens Fashion', 'Womens Fashion')], max_length=255),
        ),
        migrations.AlterField(
            model_name='our_department',
            name='Five',
            field=models.CharField(choices=[('Arts and Crafts', 'Arts and Crafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty Personal Care', 'Beauty Personal Care'), ('Books', 'Books'), ('Boys Fashion', 'Boys Fashion'), ('Computers', 'Computers'), ('Clothes', 'Clothes'), ('Dance sport', 'Dance sport'), ('Electronics', 'Electronics'), ('Girls Fashion', 'Girls Fashion'), ('Health and Household', 'Health and Household'), ('Home and Kitchen', 'Home and Kitchen'), ('Industrial and Scientific', 'Industrial and Scientific'), ('Luggage', 'Luggage'), ('Music or CDs and Vinyl', 'Music or CDs and Vinyl'), ('Movies', 'Movies'), ('Mens Fashion', 'Mens Fashion'), ('Phone and accessories', 'Phone and accessories'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Swimming', 'Swimming'), ('Television', 'Television'), ('Toys and Games', 'Toys and Games'), ('Travel', 'Travel'), ('Tools and Home Improvement', 'Tools and Home Improvement'), ('Video Games', 'Video Games'), ('Womens Fashion', 'Womens Fashion')], max_length=255),
        ),
        migrations.AlterField(
            model_name='our_department',
            name='Four',
            field=models.CharField(choices=[('Arts and Crafts', 'Arts and Crafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty Personal Care', 'Beauty Personal Care'), ('Books', 'Books'), ('Boys Fashion', 'Boys Fashion'), ('Computers', 'Computers'), ('Clothes', 'Clothes'), ('Dance sport', 'Dance sport'), ('Electronics', 'Electronics'), ('Girls Fashion', 'Girls Fashion'), ('Health and Household', 'Health and Household'), ('Home and Kitchen', 'Home and Kitchen'), ('Industrial and Scientific', 'Industrial and Scientific'), ('Luggage', 'Luggage'), ('Music or CDs and Vinyl', 'Music or CDs and Vinyl'), ('Movies', 'Movies'), ('Mens Fashion', 'Mens Fashion'), ('Phone and accessories', 'Phone and accessories'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Swimming', 'Swimming'), ('Television', 'Television'), ('Toys and Games', 'Toys and Games'), ('Travel', 'Travel'), ('Tools and Home Improvement', 'Tools and Home Improvement'), ('Video Games', 'Video Games'), ('Womens Fashion', 'Womens Fashion')], max_length=255),
        ),
        migrations.AlterField(
            model_name='our_department',
            name='One',
            field=models.CharField(choices=[('Arts and Crafts', 'Arts and Crafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty Personal Care', 'Beauty Personal Care'), ('Books', 'Books'), ('Boys Fashion', 'Boys Fashion'), ('Computers', 'Computers'), ('Clothes', 'Clothes'), ('Dance sport', 'Dance sport'), ('Electronics', 'Electronics'), ('Girls Fashion', 'Girls Fashion'), ('Health and Household', 'Health and Household'), ('Home and Kitchen', 'Home and Kitchen'), ('Industrial and Scientific', 'Industrial and Scientific'), ('Luggage', 'Luggage'), ('Music or CDs and Vinyl', 'Music or CDs and Vinyl'), ('Movies', 'Movies'), ('Mens Fashion', 'Mens Fashion'), ('Phone and accessories', 'Phone and accessories'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Swimming', 'Swimming'), ('Television', 'Television'), ('Toys and Games', 'Toys and Games'), ('Travel', 'Travel'), ('Tools and Home Improvement', 'Tools and Home Improvement'), ('Video Games', 'Video Games'), ('Womens Fashion', 'Womens Fashion')], max_length=255),
        ),
        migrations.AlterField(
            model_name='our_department',
            name='Three',
            field=models.CharField(choices=[('Arts and Crafts', 'Arts and Crafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty Personal Care', 'Beauty Personal Care'), ('Books', 'Books'), ('Boys Fashion', 'Boys Fashion'), ('Computers', 'Computers'), ('Clothes', 'Clothes'), ('Dance sport', 'Dance sport'), ('Electronics', 'Electronics'), ('Girls Fashion', 'Girls Fashion'), ('Health and Household', 'Health and Household'), ('Home and Kitchen', 'Home and Kitchen'), ('Industrial and Scientific', 'Industrial and Scientific'), ('Luggage', 'Luggage'), ('Music or CDs and Vinyl', 'Music or CDs and Vinyl'), ('Movies', 'Movies'), ('Mens Fashion', 'Mens Fashion'), ('Phone and accessories', 'Phone and accessories'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Swimming', 'Swimming'), ('Television', 'Television'), ('Toys and Games', 'Toys and Games'), ('Travel', 'Travel'), ('Tools and Home Improvement', 'Tools and Home Improvement'), ('Video Games', 'Video Games'), ('Womens Fashion', 'Womens Fashion')], max_length=255),
        ),
        migrations.AlterField(
            model_name='our_department',
            name='Two',
            field=models.CharField(choices=[('Arts and Crafts', 'Arts and Crafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty Personal Care', 'Beauty Personal Care'), ('Books', 'Books'), ('Boys Fashion', 'Boys Fashion'), ('Computers', 'Computers'), ('Clothes', 'Clothes'), ('Dance sport', 'Dance sport'), ('Electronics', 'Electronics'), ('Girls Fashion', 'Girls Fashion'), ('Health and Household', 'Health and Household'), ('Home and Kitchen', 'Home and Kitchen'), ('Industrial and Scientific', 'Industrial and Scientific'), ('Luggage', 'Luggage'), ('Music or CDs and Vinyl', 'Music or CDs and Vinyl'), ('Movies', 'Movies'), ('Mens Fashion', 'Mens Fashion'), ('Phone and accessories', 'Phone and accessories'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Swimming', 'Swimming'), ('Television', 'Television'), ('Toys and Games', 'Toys and Games'), ('Travel', 'Travel'), ('Tools and Home Improvement', 'Tools and Home Improvement'), ('Video Games', 'Video Games'), ('Womens Fashion', 'Womens Fashion')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Arts and Crafts', 'Arts and Crafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty Personal Care', 'Beauty Personal Care'), ('Books', 'Books'), ('Boys Fashion', 'Boys Fashion'), ('Computers', 'Computers'), ('Clothes', 'Clothes'), ('Dance sport', 'Dance sport'), ('Electronics', 'Electronics'), ('Girls Fashion', 'Girls Fashion'), ('Health and Household', 'Health and Household'), ('Home and Kitchen', 'Home and Kitchen'), ('Industrial and Scientific', 'Industrial and Scientific'), ('Luggage', 'Luggage'), ('Music or CDs and Vinyl', 'Music or CDs and Vinyl'), ('Movies', 'Movies'), ('Mens Fashion', 'Mens Fashion'), ('Phone and accessories', 'Phone and accessories'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Swimming', 'Swimming'), ('Television', 'Television'), ('Toys and Games', 'Toys and Games'), ('Travel', 'Travel'), ('Tools and Home Improvement', 'Tools and Home Improvement'), ('Video Games', 'Video Games'), ('Womens Fashion', 'Womens Fashion')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recommendations_for_you',
            name='category',
            field=models.CharField(choices=[('Arts and Crafts', 'Arts and Crafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty Personal Care', 'Beauty Personal Care'), ('Books', 'Books'), ('Boys Fashion', 'Boys Fashion'), ('Computers', 'Computers'), ('Clothes', 'Clothes'), ('Dance sport', 'Dance sport'), ('Electronics', 'Electronics'), ('Girls Fashion', 'Girls Fashion'), ('Health and Household', 'Health and Household'), ('Home and Kitchen', 'Home and Kitchen'), ('Industrial and Scientific', 'Industrial and Scientific'), ('Luggage', 'Luggage'), ('Music or CDs and Vinyl', 'Music or CDs and Vinyl'), ('Movies', 'Movies'), ('Mens Fashion', 'Mens Fashion'), ('Phone and accessories', 'Phone and accessories'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Swimming', 'Swimming'), ('Television', 'Television'), ('Toys and Games', 'Toys and Games'), ('Travel', 'Travel'), ('Tools and Home Improvement', 'Tools and Home Improvement'), ('Video Games', 'Video Games'), ('Womens Fashion', 'Womens Fashion')], max_length=255),
        ),
        migrations.AlterField(
            model_name='swiber_bags',
            name='category',
            field=models.CharField(choices=[('Arts and Crafts', 'Arts and Crafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty Personal Care', 'Beauty Personal Care'), ('Books', 'Books'), ('Boys Fashion', 'Boys Fashion'), ('Computers', 'Computers'), ('Clothes', 'Clothes'), ('Dance sport', 'Dance sport'), ('Electronics', 'Electronics'), ('Girls Fashion', 'Girls Fashion'), ('Health and Household', 'Health and Household'), ('Home and Kitchen', 'Home and Kitchen'), ('Industrial and Scientific', 'Industrial and Scientific'), ('Luggage', 'Luggage'), ('Music or CDs and Vinyl', 'Music or CDs and Vinyl'), ('Movies', 'Movies'), ('Mens Fashion', 'Mens Fashion'), ('Phone and accessories', 'Phone and accessories'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Swimming', 'Swimming'), ('Television', 'Television'), ('Toys and Games', 'Toys and Games'), ('Travel', 'Travel'), ('Tools and Home Improvement', 'Tools and Home Improvement'), ('Video Games', 'Video Games'), ('Womens Fashion', 'Womens Fashion')], max_length=255),
        ),
    ]
