# Generated by Django 3.1.1 on 2020-09-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Bio',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bio Or Stuts'),
        ),
        migrations.AddField(
            model_name='customer',
            name='image_Cover',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Cover'),
        ),
    ]
