# Generated by Django 3.1.1 on 2020-09-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200925_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Bio',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Bio Or Stuts'),
        ),
    ]
