# Generated by Django 3.1.1 on 2020-09-26 02:09

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200926_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Bio',
            field=models.TextField(blank=True, max_length=605, verbose_name='Bio Or Stuts'),
        ),
    ]
